### ISSUE TITLE
pyenv is not put in PATH

### ISSUE THREAD

**Issue by alexey-guryanov** [dirn/ansible-pyenv#3]
Even though there is a task putting pyenv bin directory into PATH, but the code it produces is executed only if pyenv is already in PATH (basically it is never executed):

```
    - if which pyenv > /dev/null; then
    - "    export PYENV_ROOT=\\\"$HOME/.pyenv\\\""
    - "    export PATH=\\\"$PYENV_ROOT/bin:$PATH\\\""
    - "    eval \\\"$(pyenv init -)\\\""
    - "fi # pyenv"
```

**Comment by blueyed** [comment]
Yep, seems to be duplicate of #1.

**Comment by dirn** [comment]
Closing as duplicate.
